from . import achievement
from . import app_bootstrap
from . import character
from . import debug
from . import economy
from . import friend
from . import graduation
from . import minigame
from . import quiz
from . import room
from . import school_food
from . import shop
from . import user
from . import user_quiz_connect
